name: Basic Commands
    - main
    schedule:
      -cron: "00***"
  
jobs:
  demo-commands:
    runs-on:ubuntu-latest

    steps:
      - name: Show current working directory
      run: pwd

      
      
